stages:
  - deploy
  
DokkuDeployment:
  image: dokku/ci-docker-image
  stage: deploy
  environment:
    name: production
    url: $APP_HOST:$APP_PORT
  tags:
    - dokku
  only:
    - main
  variables:
    GIT_REMOTE_URL: ssh://dokku@$APP_HOST:22/$APP_NAME
        # enable verbose git output
    GIT_PUSH_FLAGS: '-vvv'
    # enable verbose ssh output
    GIT_SSH_COMMAND: 'ssh -vvv'
    GIT_DEPTH: 0
  script:
    - dokku-deploy
  after_script: [dokku-unlock]
