version: '3'

services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
    stratis-ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        ports:
            - "3000:3000"