version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"

  stratis-next-js:
    depends_on:
      - app
    build:
      context: ./ui
      dockerfile: Dockerfile
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - stratis-next-js
    ports:
      - "${NGINX_PORT:-3000}:80"