- name: Run pytest
  # You may pin to the exact commit or the version.
  # uses: pavelzw/pytest-action@99552c37a65b8b15daa244f477fd88660a2ae95e
  uses: pavelzw/pytest-action@v2.0.0
  with:
    # Print a GitHub job summary
    job-summary: # optional, default is true
    # Verbose output
    verbose: # optional, default is true
    # Use emojis in the output
    emoji: # optional, default is true
    # Custom arguments to pass to pytest
    custom-arguments: # optional, default is 
    # Title of the report
    report-title: # optional, default is Test Report
    # Add 'Click to expand' to the report
    click-to-expand: # optional, default is true
